// @generated by the web build (gen-embed.mjs) — do not edit.
pub fn asset(path: &str) -> Option<(&'static str, &'static str, &'static [u8])> {
    Some(match path {
        "/assets/EmojiPicker-CuVSX2B2.js" => (
            "text/javascript; charset=UTF-8", "gzip", include_bytes!("assets/EmojiPicker-CuVSX2B2.js.gz")),
        "/assets/index-CjPCHYYX.js" => (
            "text/javascript; charset=UTF-8", "gzip", include_bytes!("assets/index-CjPCHYYX.js.gz")),
        "/assets/index-Dvvkf9iP.css" => (
            "text/css; charset=UTF-8", "gzip", include_bytes!("assets/index-Dvvkf9iP.css.gz")),
        "/emoji.db" => (
            "application/octet-stream", "gzip", include_bytes!("emoji.db.gz")),
        "/favicon-dark.svg" => (
            "image/svg+xml", "gzip", include_bytes!("favicon-dark.svg.gz")),
        "/favicon-light.svg" => (
            "image/svg+xml", "gzip", include_bytes!("favicon-light.svg.gz")),
        "/favicon.ico" => (
            "image/x-icon", "gzip", include_bytes!("favicon.ico.gz")),
        "/" | "/index.html" => (
            "text/html; charset=UTF-8", "gzip", include_bytes!("index.html.gz")),
        _ => return None,
    })
}
