use std::error::Error;
use std::ffi::OsStr;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

type Ret<T> = Result<T, Box<dyn Error>>;

const DEFAULT_PREFIX: &str = "icon-";

struct Config {
    input_dir: PathBuf,
    output: PathBuf,
    prefix: String,
}

struct SourceIcon {
    name: String,
    view_box: String,
    attrs: Vec<(&'static str, String)>,
    inner: String,
}

fn main() -> Ret<()> {
    let config = parse_args()?;
    ensure_tool("resvg")?;

    let temp_dir = make_temp_dir()?;
    let result = generate_module(&config, &temp_dir);
    let cleanup = std::fs::remove_dir_all(&temp_dir);
    match (result, cleanup) {
        (Err(err), _) => Err(err),
        (Ok(_), Err(err)) => Err(format!("failed to remove {}: {err}", temp_dir.display()).into()),
        (Ok(()), Ok(())) => Ok(()),
    }
}

fn parse_args() -> Ret<Config> {
    let mut prefix = DEFAULT_PREFIX.to_string();
    let mut positional = Vec::new();
    let mut args = std::env::args().skip(1);

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--help" | "-h" => {
                print_help();
                std::process::exit(0);
            }
            "--prefix" => {
                prefix = args.next().ok_or("missing value after --prefix")?;
                if prefix.is_empty() {
                    return Err("--prefix must not be empty".into());
                }
            }
            _ if arg.starts_with("--") => return Err(format!("unknown option {arg}").into()),
            _ => positional.push(PathBuf::from(arg)),
        }
    }

    if positional.len() != 2 {
        print_help();
        return Err("expected INPUT_DIR and OUTPUT_TS".into());
    }

    Ok(Config {
        input_dir: positional.remove(0),
        output: positional.remove(0),
        prefix,
    })
}

fn print_help() {
    eprintln!(
        "usage: pathify_svg [--prefix PREFIX] INPUT_DIR OUTPUT_TS\n\
         builds a bundled TypeScript SVG symbol sprite from source icons"
    );
}

fn ensure_tool(name: &str) -> Ret<()> {
    let status = Command::new(name)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
    match status {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => Err(format!("{name} --version exited with {status}").into()),
        Err(err) => Err(format!("{name} is required: {err}").into()),
    }
}

fn make_temp_dir() -> Ret<PathBuf> {
    let mut dir = std::env::temp_dir();
    dir.push(format!(
        "pathify-svg-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

fn generate_module(config: &Config, temp_dir: &Path) -> Ret<()> {
    let mut files = svg_files(&config.input_dir)?;
    files.sort();

    let mut icon_names = Vec::with_capacity(files.len());
    let mut sprite = String::with_capacity(files.len() * 256);
    sprite.push_str(
        r#"<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">"#,
    );

    for file in files {
        let icon = read_icon(&file)?;
        validate_icon(temp_dir, &icon)?;
        icon_names.push(icon.name.clone());
        write!(
            sprite,
            r#"<symbol id="{}{}" viewBox="{}""#,
            config.prefix, icon.name, icon.view_box
        )?;
        for (name, value) in &icon.attrs {
            write!(sprite, r#" {name}="{}""#, escape_attr(value))?;
        }
        sprite.push('>');
        sprite.push_str(&icon.inner);
        sprite.push_str("</symbol>");
    }

    sprite.push_str("</svg>");

    let mut module = String::new();
    module.push_str("// Generated by crates/pathify_svg. Do not edit by hand.\n");
    module.push_str("export const ICON_PREFIX = ");
    write!(module, "{:?}", config.prefix)?;
    module.push_str(";\n");
    module.push_str("export const ICON_NAMES = [");
    for (index, name) in icon_names.iter().enumerate() {
        if index > 0 {
            module.push_str(", ");
        }
        write!(module, "{name:?}")?;
    }
    module.push_str("] as const;\n");
    module.push_str("export type IconName = (typeof ICON_NAMES)[number];\n");
    module.push_str("export const ICON_SPRITE = ");
    write!(module, "{sprite:?}")?;
    module.push_str(";\n");
    std::fs::write(&config.output, module)?;
    Ok(())
}

fn svg_files(dir: &Path) -> Ret<Vec<PathBuf>> {
    let mut files = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension() == Some(OsStr::new("svg")) {
            files.push(path);
        }
    }
    if files.is_empty() {
        return Err(format!("no .svg files found in {}", dir.display()).into());
    }
    Ok(files)
}

fn read_icon(file: &Path) -> Ret<SourceIcon> {
    let svg = std::fs::read_to_string(file)?;
    let (svg_tag, inner_start) = open_tag(&svg, "svg").ok_or("missing <svg>")?;
    let inner_end = svg.rfind("</svg>").ok_or("missing </svg>")?;
    if inner_end < inner_start {
        return Err(format!("invalid svg wrapper in {}", file.display()).into());
    }

    let view_box =
        attr(svg_tag, "viewBox").ok_or_else(|| format!("{} is missing viewBox", file.display()))?;
    validate_view_box(&view_box)?;

    let mut attrs = Vec::new();
    for name in [
        "fill",
        "stroke",
        "stroke-width",
        "stroke-linecap",
        "stroke-linejoin",
    ] {
        if let Some(value) = attr(svg_tag, name) {
            attrs.push((name, value));
        }
    }

    let inner = minify_inner(&svg[inner_start..inner_end])?;
    if inner.is_empty() {
        return Err(format!("{} has no drawable content", file.display()).into());
    }

    Ok(SourceIcon {
        name: icon_name(file)?,
        view_box,
        attrs,
        inner,
    })
}

fn open_tag<'a>(xml: &'a str, name: &str) -> Option<(&'a str, usize)> {
    let needle = format!("<{name}");
    let start = xml.find(&needle)?;
    let end = xml[start..].find('>')?;
    let end = start + end + 1;
    Some((&xml[start..end], end))
}

fn validate_view_box(raw: &str) -> Ret<()> {
    let nums = raw
        .split(|ch: char| ch.is_ascii_whitespace() || ch == ',')
        .filter(|part| !part.is_empty())
        .map(str::parse::<f64>)
        .collect::<Result<Vec<_>, _>>()?;
    if nums.len() != 4 || nums.iter().any(|n| !n.is_finite()) {
        return Err(format!("invalid viewBox {raw:?}").into());
    }
    if nums[2] <= 0.0 || nums[3] <= 0.0 {
        return Err(format!("invalid viewBox dimensions {raw:?}").into());
    }
    Ok(())
}

fn attr(tag: &str, name: &str) -> Option<String> {
    let bytes = tag.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        while i < bytes.len() && !is_attr_name_start(bytes[i]) {
            i += 1;
        }
        let start = i;
        while i < bytes.len() && is_attr_name_char(bytes[i]) {
            i += 1;
        }
        if start == i {
            break;
        }
        let attr_name = &tag[start..i];
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= bytes.len() || bytes[i] != b'=' {
            continue;
        }
        i += 1;
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= bytes.len() || (bytes[i] != b'"' && bytes[i] != b'\'') {
            continue;
        }
        let quote = bytes[i];
        i += 1;
        let value_start = i;
        while i < bytes.len() && bytes[i] != quote {
            i += 1;
        }
        if attr_name == name {
            return Some(xml_unescape(&tag[value_start..i]));
        }
        i += 1;
    }
    None
}

fn is_attr_name_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || byte == b'_' || byte == b':'
}

fn is_attr_name_char(byte: u8) -> bool {
    is_attr_name_start(byte) || byte.is_ascii_digit() || byte == b'.' || byte == b'-'
}

fn minify_inner(inner: &str) -> Ret<String> {
    let mut output = String::new();
    let mut in_comment = false;
    for raw_line in inner.lines() {
        let line = raw_line.trim();
        if line.is_empty() {
            continue;
        }
        if in_comment {
            if line.contains("-->") {
                in_comment = false;
            }
            continue;
        }
        if line.starts_with("<!--") {
            if !line.contains("-->") {
                in_comment = true;
            }
            continue;
        }
        if line.contains("<script") || line.contains("</script") {
            return Err("script tags are not allowed in icons".into());
        }
        output.push_str(line);
    }
    Ok(output)
}

fn icon_name(file: &Path) -> Ret<String> {
    let stem = file
        .file_stem()
        .and_then(OsStr::to_str)
        .ok_or_else(|| format!("invalid icon file name {}", file.display()))?;
    let stem = stem
        .strip_prefix("iconmonstr-")
        .unwrap_or(stem)
        .strip_suffix("-1")
        .unwrap_or(stem);
    let mut name = String::new();
    let mut last_dash = false;
    for ch in stem.chars().flat_map(char::to_lowercase) {
        if ch.is_ascii_alphanumeric() {
            name.push(ch);
            last_dash = false;
        } else if !last_dash {
            name.push('-');
            last_dash = true;
        }
    }
    while name.ends_with('-') {
        name.pop();
    }
    if name.is_empty() {
        return Err(format!("icon name for {} is empty", file.display()).into());
    }
    Ok(name)
}

fn validate_icon(temp_dir: &Path, icon: &SourceIcon) -> Ret<()> {
    let svg_path = temp_dir.join(format!("{}.svg", icon.name));
    let png_path = temp_dir.join(format!("{}.png", icon.name));
    let mut svg = String::new();
    write!(
        svg,
        r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="{}""#,
        icon.view_box
    )?;
    for (name, value) in &icon.attrs {
        write!(svg, r#" {name}="{}""#, escape_attr(value))?;
    }
    svg.push('>');
    svg.push_str(&icon.inner);
    svg.push_str("</svg>");
    std::fs::write(&svg_path, svg)?;

    let output = Command::new("resvg")
        .arg(&svg_path)
        .arg(&png_path)
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "resvg failed to render {} with {}\n{}",
            icon.name,
            output.status,
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }
    Ok(())
}

fn xml_unescape(value: &str) -> String {
    value
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
}

fn escape_attr(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}
