//! The browser chat-log view served over [`darkhttp`].
//!
//! A dedicated thread owns the [`Server`] and runs its blocking poll loop. The
//! app forwards messages through a [`WebFeedSender`], which delivers them over an
//! `mpsc` channel and wakes the loop via a [`darkhttp::WakeHandle`] so they
//! broadcast immediately. On connect a client receives a recent window of
//! history, then a frame per new message. A browser pages older history on
//! demand by sending a `load_older` request as it scrolls up, addressed by a
//! server-assigned monotonic sequence number.

use std::fs;
use std::io;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::mpsc::{self, Receiver, Sender, TryRecvError};
use std::thread;
use std::time::Duration;

use darkhttp::{
    Router, Server, ServerConfig, ServerEvent, WakeHandle, WebSocketId, WebSocketMessage,
};
use jsony::Jsony;
use rpc::control::{ChatMessage, FileMetadata};

use crate::config::WebConfig;
use crate::web_wire::{self, Fragment, split_fragments};

/// The path a browser opens a WebSocket on for the live feed.
const WS_PATH: &str = "/ws";
#[cfg(not(feature = "embed-web"))]
const WEB_ASSETS_DIR: &str = "web/dist";

/// The frontend compiled into the binary under the `embed-web` feature. The
/// `asset` resolver is generated by the web build into `web/dist/embed.rs`.
#[cfg(feature = "embed-web")]
mod embed {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/embed.rs"));
}

/// How many of the most recent messages a fresh `sync` frame carries. Older
/// history is paged in on demand.
const SYNC_WINDOW: usize = 100;

/// Upper bound on the messages one `load_older` request can return, so a
/// misbehaving client cannot ask for an unbounded slice.
const MAX_PAGE: usize = 200;

/// Largest UTF-8 file the highlighted preview endpoint will read and encode.
const MAX_HIGHLIGHT_FILE_BYTES: u64 = 2 * 1024 * 1024;

/// A single chat entry the frontend renders.
///
/// The body is split into [`Fragment`]s (prose and highlighted code) that the
/// browser composes directly. The wire form is the binary encoding in
/// [`crate::web_wire`], not JSON.
#[derive(Clone)]
pub struct WebMessage {
    pub id: u64,
    pub sender: String,
    pub timestamp_ms: u64,
    pub attachment: Option<WebAttachment>,
    /// `Some` for a file message. The feed upserts by this id together with
    /// `timestamp_ms`, because transfer ids are reused after a server restart.
    pub file_id: Option<u64>,
    /// The body pre-split into prose and highlighted code fragments.
    pub fragments: Vec<Fragment>,
}

/// An inline media file attached to a [`WebMessage`], served from `/files`.
#[derive(Clone)]
pub struct WebAttachment {
    /// The served file name. The frontend builds the URL as `/files/<name>`.
    pub name: String,
    /// One of `image`, `video`, `audio`, or `file`.
    pub kind: String,
    /// Intrinsic pixel width, set for `image` attachments whose header parsed.
    ///
    /// The frontend reserves the box from `width`/`height` so a decoding image
    /// never grows the layout. `None` for non-images or an unreadable header.
    pub width: Option<u32>,
    /// Intrinsic pixel height, paired with [`width`](WebAttachment::width).
    pub height: Option<u32>,
}

impl From<&ChatMessage> for WebMessage {
    fn from(message: &ChatMessage) -> Self {
        let file_id = message.file_transfer_id.map(|transfer_id| transfer_id.0);
        WebMessage {
            // A file announcement keys on the transfer id so it shares an id with
            // the inline file message that later enriches it.
            id: file_id.unwrap_or(message.message_id.0),
            sender: message.sender_name.clone(),
            fragments: split_fragments(&message.body),
            timestamp_ms: message.timestamp_ms,
            attachment: None,
            file_id,
        }
    }
}

impl WebMessage {
    /// Builds a message representing a received file, with an inline attachment.
    ///
    /// `served_name` is the file's actual name on disk under the receive
    /// directory, which is what `/files/<name>` resolves. It can differ from
    /// `metadata.file_name` when a name collision was renamed on save.
    ///
    /// `dimensions`, when set, is the intrinsic pixel size of an image. It is
    /// recorded only for the `image` kind so the frontend can reserve the box.
    pub fn from_file(
        metadata: &FileMetadata,
        served_name: &str,
        dimensions: Option<(u32, u32)>,
    ) -> Self {
        let kind = classify(served_name);
        let (width, height) = match (kind, dimensions) {
            ("image", Some((w, h))) => (Some(w), Some(h)),
            _ => (None, None),
        };
        // Mirror the server's announcement body so the size metadata survives
        // whichever of the two messages wins the upsert merge.
        let body = format!(
            "sent file `{}` ({})",
            metadata.original_name,
            format_size(metadata.size)
        );
        WebMessage {
            id: metadata.transfer_id.0,
            sender: metadata.sender_name.clone(),
            fragments: split_fragments(&body),
            timestamp_ms: metadata.timestamp_ms,
            attachment: Some(WebAttachment {
                kind: kind.to_string(),
                name: served_name.to_string(),
                width,
                height,
            }),
            file_id: Some(metadata.transfer_id.0),
        }
    }
}

impl WebMessage {
    /// Builds a file message from persisted history: the chat announcement plus
    /// the stored served name and image dimensions. Used to populate the web
    /// backlog with a room's file messages when the room is entered.
    pub fn from_history_file(
        message: &ChatMessage,
        served_name: &str,
        dimensions: Option<(u32, u32)>,
    ) -> Self {
        let kind = classify(served_name);
        let (width, height) = match (kind, dimensions) {
            ("image", Some((w, h))) => (Some(w), Some(h)),
            _ => (None, None),
        };
        let file_id = message.file_transfer_id.map(|transfer_id| transfer_id.0);
        WebMessage {
            id: file_id.unwrap_or(message.message_id.0),
            sender: message.sender_name.clone(),
            fragments: split_fragments(&message.body),
            timestamp_ms: message.timestamp_ms,
            attachment: Some(WebAttachment {
                kind: kind.to_string(),
                name: served_name.to_string(),
                width,
                height,
            }),
            file_id,
        }
    }
}

impl WebMessage {
    /// Folds a later message for the same file into this one. Order-independent:
    /// the incoming fields win, but an attachment is never dropped, so the inline
    /// version's media survives whether it arrives before or after the
    /// announcement placeholder.
    fn merge_from(&mut self, incoming: WebMessage) {
        let attachment = incoming.attachment.or_else(|| self.attachment.take());
        *self = WebMessage {
            attachment,
            ..incoming
        };
    }
}

#[cfg(test)]
impl WebMessage {
    /// A plain text message with a fixed sender and timestamp, for tests.
    pub(crate) fn text_for_test(id: u64, body: &str) -> Self {
        WebMessage {
            id,
            sender: "Alice".to_string(),
            fragments: split_fragments(body),
            timestamp_ms: 100,
            attachment: None,
            file_id: None,
        }
    }
}

fn same_file(left: &WebMessage, right: &WebMessage) -> bool {
    left.file_id.is_some()
        && left.file_id == right.file_id
        && left.timestamp_ms == right.timestamp_ms
}

/// Formats a byte count the way the server's file announcement does, so an
/// enriched file message reads identically to its placeholder.
fn format_size(bytes: u64) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * KIB;
    if bytes >= MIB {
        format!("{:.1} MiB", bytes as f64 / MIB as f64)
    } else if bytes >= KIB {
        format!("{:.1} KiB", bytes as f64 / KIB as f64)
    } else {
        format!("{bytes} B")
    }
}

/// Reads the intrinsic pixel size of an image from a prefix of its bytes.
///
/// Parses only the header fields, so a leading slice of the file is enough. The
/// caller captures that slice as the transfer streams, so the bytes are never
/// read from disk a second time. Returns `None` when `header` is not a
/// recognized image or is too short to hold the dimensions.
pub fn image_dimensions(header: &[u8]) -> Option<(u32, u32)> {
    let size = imagesize::blob_size(header).ok()?;
    Some((size.width as u32, size.height as u32))
}

/// Classifies a file name into a media kind by its extension.
pub(crate) fn classify(name: &str) -> &'static str {
    let extension = name.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match extension.as_str() {
        "png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp" | "svg" | "avif" => "image",
        "mp4" | "webm" | "mov" | "mkv" => "video",
        "mp3" | "ogg" | "opus" | "wav" | "flac" | "m4a" | "aac" => "audio",
        _ => "file",
    }
}

/// What the app sends to the web thread.
enum WebFeed {
    Message(WebMessage),
    /// Replaces the backlog with the current room's messages (empty when there
    /// is no current room) and re-syncs every connected browser. The web view
    /// mirrors the room the client is in, nothing more.
    SetRoom(Vec<WebMessage>),
    /// A `share_available` envelope. The web thread retains it by `stream_id` and
    /// replays it to a browser that connects after the share started.
    ShareAvailable {
        stream_id: u32,
        payload: String,
    },
    /// A `share_config` envelope sent when playback starts. Transient: it targets
    /// a browser that already asked to play, so it is broadcast but not retained.
    ShareConfig(String),
    /// A `share_error` envelope reporting a failed play request. Transient and
    /// broadcast like [`ShareConfig`](WebFeed::ShareConfig), not retained.
    ShareError(String),
    /// A `file_progress` envelope for an in-flight transfer. Transient: browsers
    /// merge it into the matching placeholder message and it is not retained, so a
    /// browser that connects mid-transfer simply sees the file once it lands.
    FileProgress(String),
    /// A `share_ended` envelope. Drops the retained `share_available` for its
    /// `stream_id`.
    ShareEnded {
        stream_id: u32,
        payload: String,
    },
    /// One plaintext video frame body (the 17-byte header plus the bitstream),
    /// forwarded to browsers as a binary WebSocket message without re-framing.
    VideoFrame(Vec<u8>),
    Stop,
}

/// A request a browser sends back to the app, forwarded over the web-to-app
/// channel. Screen-share playback is browser-initiated, so a play click must
/// reach the app to spawn the viewer connection.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum WebRequest {
    PlayShare {
        stream_id: u32,
    },
    StopShare {
        stream_id: u32,
    },
    /// A chat line the browser composed, sent to the current room.
    SendChat {
        body: String,
    },
    /// A file the browser uploaded, reassembled to `path` on disk.
    UploadFile {
        path: PathBuf,
    },
}

/// A request a browser sends over the WebSocket as a JSON text frame.
#[derive(Jsony)]
#[jsony(Json, tag = "type")]
enum ClientRequest {
    /// Asks for up to `limit` messages immediately older than `before_seq`.
    #[jsony(rename = "load_older")]
    LoadOlder { before_seq: u64, limit: u64 },
    /// Asks the app to start streaming a screen share into this browser.
    #[jsony(rename = "play_share")]
    PlayShare { stream_id: u32 },
    /// Asks the app to stop streaming a screen share.
    #[jsony(rename = "stop_share")]
    StopShare { stream_id: u32 },
    /// A composed chat line to send to the current room. Ignored when read-only.
    #[jsony(rename = "send_message")]
    SendMessage { body: String },
    /// Opens a file upload. The binary chunk frames that follow carry its bytes,
    /// keyed by `upload_id`, and `upload_finish` closes it. Ignored when
    /// read-only.
    #[jsony(rename = "upload_start")]
    UploadStart {
        upload_id: u32,
        name: String,
        size: u64,
    },
    /// Closes the upload opened with the matching `upload_id`, queuing the
    /// reassembled file for sending.
    #[jsony(rename = "upload_finish")]
    UploadFinish { upload_id: u32 },
}

/// A cloneable handle the app uses to push messages to the web view.
///
/// [`send`](WebFeedSender::send) queues the message and wakes the server's poll
/// loop, so a connected browser sees it without any polling delay. Sends never
/// fail loudly: a dead web thread must not break the chat client.
#[derive(Clone)]
pub struct WebFeedSender {
    tx: Sender<WebFeed>,
    wake: WakeHandle,
}

impl WebFeedSender {
    /// Pushes a message to every connected browser and records it in history.
    pub fn send(&self, message: WebMessage) {
        let _ = self.tx.send(WebFeed::Message(message));
        self.wake.wake();
    }

    /// Replaces the feed's backlog with `messages` and re-syncs every browser.
    ///
    /// Call this on entering a room (with that room's history) and on leaving
    /// one (with an empty vector) so the web view always shows exactly the
    /// current room's content.
    pub fn set_room(&self, messages: Vec<WebMessage>) {
        let _ = self.tx.send(WebFeed::SetRoom(messages));
        self.wake.wake();
    }

    /// Announces a screen share to every browser, retained so a browser that
    /// connects later still learns the share is available.
    pub fn send_share_available(&self, stream_id: u32, payload: String) {
        let _ = self.tx.send(WebFeed::ShareAvailable { stream_id, payload });
        self.wake.wake();
    }

    /// Sends a decoder-config envelope when playback starts. Not retained.
    pub fn send_share_config(&self, payload: String) {
        let _ = self.tx.send(WebFeed::ShareConfig(payload));
        self.wake.wake();
    }

    /// Sends a play-failure envelope to the browser. Not retained.
    pub fn send_share_error(&self, payload: String) {
        let _ = self.tx.send(WebFeed::ShareError(payload));
        self.wake.wake();
    }

    /// Broadcasts a file-transfer progress envelope. Not retained: browsers merge
    /// it into the matching placeholder message.
    pub fn send_file_progress(&self, payload: String) {
        let _ = self.tx.send(WebFeed::FileProgress(payload));
        self.wake.wake();
    }

    /// Tells every browser a share ended and drops its retained announcement.
    pub fn send_share_ended(&self, stream_id: u32, payload: String) {
        let _ = self.tx.send(WebFeed::ShareEnded { stream_id, payload });
        self.wake.wake();
    }

    /// Sends one plaintext video frame body as a binary WebSocket message.
    pub fn send_video_frame(&self, frame: Vec<u8>) {
        let _ = self.tx.send(WebFeed::VideoFrame(frame));
        self.wake.wake();
    }

    pub fn stop(&self) {
        let _ = self.tx.send(WebFeed::Stop);
        self.wake.wake();
    }
}

/// Builds the `/highlight/<name>` handler serving a file's line-indexed
/// highlight buffer (see [`crate::highlight::encode_file`]).
///
/// The name resolves against `dir`, the same flat receive directory `/files`
/// serves. A missing file is `404`, a file over [`MAX_HIGHLIGHT_FILE_BYTES`] is
/// `413`, a non-UTF-8 file is `415`, and any text file returns the binary
/// buffer regardless of whether its extension maps to a highlighter (an unknown
/// extension renders as plain text).
fn highlight_route(dir: PathBuf) -> darkhttp::GeneratedHandler {
    Arc::new(move |request: &darkhttp::GeneratedRequest| {
        let name = request.relative;
        // The receive directory is flat, so a name with a separator or parent
        // reference is never valid and is refused rather than resolved.
        if !valid_highlight_name(name) {
            return darkhttp::GeneratedResponse::error(404);
        }
        let path = dir.join(name);
        let Ok(metadata) = fs::metadata(&path) else {
            return darkhttp::GeneratedResponse::error(404);
        };
        if !metadata.is_file() {
            return darkhttp::GeneratedResponse::error(404);
        }
        if metadata.len() > MAX_HIGHLIGHT_FILE_BYTES {
            return darkhttp::GeneratedResponse::error(413);
        }
        let Ok(bytes) = fs::read(&path) else {
            return darkhttp::GeneratedResponse::error(404);
        };
        if bytes.len() as u64 > MAX_HIGHLIGHT_FILE_BYTES {
            return darkhttp::GeneratedResponse::error(413);
        }
        let Ok(text) = String::from_utf8(bytes) else {
            return darkhttp::GeneratedResponse::error(415);
        };
        let language = crate::highlight::language_for_path(name);
        let buffer = crate::highlight::encode_file(&text, language);
        darkhttp::GeneratedResponse::ok("application/octet-stream", buffer)
    })
}

fn valid_highlight_name(name: &str) -> bool {
    !name.is_empty() && name != "." && name != ".." && !name.contains('/') && !name.contains('\\')
}

/// Starts the web server on its own thread and returns a feed handle.
///
/// `receive_dir`, when set, is mounted at `/files` so inline media resolves.
/// `max_messages` bounds the in-memory history replayed to new clients.
///
/// # Errors
///
/// Returns an error if `cfg.bind` is not a valid socket address or the listener
/// cannot bind.
pub fn spawn(
    cfg: &WebConfig,
    receive_dir: Option<PathBuf>,
    max_messages: usize,
    web_requests: Sender<WebRequest>,
    readonly: bool,
) -> io::Result<WebFeedSender> {
    let addr: SocketAddr = cfg.bind.parse().map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid web.bind `{}`: {error}", cfg.bind),
        )
    })?;

    let mut router = Router::new().websocket(WS_PATH);
    if let Some(dir) = receive_dir {
        router = router
            .mount_file_dir("/files", dir.clone())
            .mount_generated("/highlight", highlight_route(dir));
    }
    #[cfg(not(feature = "embed-web"))]
    {
        router = router.mount_static_dir("/", PathBuf::from(WEB_ASSETS_DIR));
    }
    #[cfg(feature = "embed-web")]
    {
        router = router.embedded_assets(embed::asset);
    }

    // A zero timeout disables idle-connection reaping so a quiet WebSocket is
    // never closed out from under a watching browser.
    let config = ServerConfig::default().bind(addr).timeout(Duration::ZERO);
    let server = Server::bind(config, router)?;
    let wake = server.wake_handle()?;
    let local = server.local_addr()?;

    let (tx, rx) = mpsc::channel();
    thread::Builder::new()
        .name("web-server".to_string())
        .spawn(move || run(server, rx, max_messages, web_requests, readonly))?;

    kvlog::info!("web server listening", addr = %local);
    Ok(WebFeedSender { tx, wake })
}

/// The web thread's event loop. Blocks until a socket event or a feed wake.
fn run(
    mut server: Server,
    rx: Receiver<WebFeed>,
    max_messages: usize,
    web_requests: Sender<WebRequest>,
    readonly: bool,
) {
    // Open uploads keyed by connection and browser-assigned id, each an
    // append-mode file the binary chunk frames stream into until `upload_finish`.
    // Scoping by connection keeps two browsers (or a reconnect reusing an id)
    // from colliding, and lets a disconnect drop that client's in-flight files.
    // Empty and unused when read-only.
    let mut uploads: std::collections::HashMap<(WebSocketId, u32), UploadSink> =
        std::collections::HashMap::new();
    let mut history: Vec<WebMessage> = Vec::new();
    // The sequence number of `history[0]`. Sequence numbers are monotonic across
    // the whole feed and survive front-draining, so a browser can address older
    // history independent of the message ids (which span two id namespaces).
    let mut base_seq: u64 = 0;
    let mut clients: Vec<WebSocketId> = Vec::new();
    // Active screen shares by stream id, replayed to a browser that connects
    // after a share started so it still shows the play button.
    let mut active_shares: std::collections::HashMap<u32, String> =
        std::collections::HashMap::new();

    loop {
        if let Err(error) = server.poll_once(None) {
            kvlog::error!("web server poll failed", error = %error);
            return;
        }

        for event in server.drain_events() {
            match event {
                ServerEvent::WebSocketOpen { id, path } => {
                    if path == WS_PATH {
                        clients.push(id);
                        let _ = server.send_websocket_binary(id, &sync_frame(&history, base_seq));
                        let _ = server.send_websocket_text(id, &config_envelope(readonly));
                        for payload in active_shares.values() {
                            let _ = server.send_websocket_text(id, payload);
                        }
                    }
                }
                ServerEvent::WebSocketClose { id } => {
                    clients.retain(|client| *client != id);
                    // Drop and delete any uploads this client left unfinished.
                    uploads.retain(|(client, _), sink| {
                        if *client == id {
                            let _ = fs::remove_file(&sink.path);
                            false
                        } else {
                            true
                        }
                    });
                }
                ServerEvent::WebSocketMessage {
                    id,
                    message: WebSocketMessage::Text(text),
                } => match jsony::from_json::<ClientRequest>(&text) {
                    Ok(ClientRequest::LoadOlder { before_seq, limit }) => {
                        let frame = older_frame(before_seq, limit, &history, base_seq);
                        let _ = server.send_websocket_binary(id, &frame);
                    }
                    Ok(ClientRequest::PlayShare { stream_id }) => {
                        let _ = web_requests.send(WebRequest::PlayShare { stream_id });
                    }
                    Ok(ClientRequest::StopShare { stream_id }) => {
                        let _ = web_requests.send(WebRequest::StopShare { stream_id });
                    }
                    // Writes are refused wholesale in read-only mode, matching a
                    // browser that never shows the compose box.
                    Ok(ClientRequest::SendMessage { body }) if !readonly => {
                        let _ = web_requests.send(WebRequest::SendChat { body });
                    }
                    Ok(ClientRequest::UploadStart {
                        upload_id,
                        name,
                        size: _,
                    }) if !readonly => match UploadSink::create(upload_id, &name) {
                        Ok(sink) => {
                            uploads.insert((id, upload_id), sink);
                        }
                        Err(error) => {
                            kvlog::warn!("web upload could not be opened", error = %error);
                        }
                    },
                    Ok(ClientRequest::UploadFinish { upload_id }) if !readonly => {
                        if let Some(sink) = uploads.remove(&(id, upload_id)) {
                            let _ = web_requests.send(WebRequest::UploadFile { path: sink.path });
                        }
                    }
                    Ok(_) | Err(_) => {}
                },
                ServerEvent::WebSocketMessage {
                    id,
                    message: WebSocketMessage::Binary(payload),
                } => {
                    // A browser binary frame is one upload chunk: a little-endian
                    // `u32` id followed by the bytes to append to that upload.
                    if !readonly && payload.len() >= 4 {
                        let upload_id = u32::from_le_bytes(payload[0..4].try_into().unwrap());
                        if let Some(sink) = uploads.get_mut(&(id, upload_id)) {
                            if let Err(error) = sink.append(&payload[4..]) {
                                kvlog::warn!("web upload chunk write failed", error = %error);
                                uploads.remove(&(id, upload_id));
                            }
                        }
                    }
                }
            }
        }

        loop {
            match rx.try_recv() {
                Ok(WebFeed::Message(message)) => {
                    // A file message upserts onto its existing entry (the
                    // announcement placeholder, or the inline version if it
                    // arrived first), so a file is one message enriched in place,
                    // never two. The seq is preserved, so paging is untouched.
                    let existing = message.file_id.and_then(|_| {
                        history
                            .iter_mut()
                            .rev()
                            .find(|held| same_file(held, &message))
                    });
                    let frame = if let Some(existing) = existing {
                        existing.merge_from(message);
                        web_wire::encode_single(existing)
                    } else {
                        let frame = web_wire::encode_single(&message);
                        history.push(message);
                        if history.len() > max_messages {
                            let excess = history.len() - max_messages;
                            history.drain(0..excess);
                            base_seq += excess as u64;
                        }
                        frame
                    };
                    for id in &clients {
                        let _ = server.send_websocket_binary(*id, &frame);
                    }
                }
                Ok(WebFeed::SetRoom(messages)) => {
                    // Advance the sequence past the dropped backlog so a browser
                    // never confuses the new room's messages with the old ones,
                    // then bound the replacement to the same window as live sends.
                    base_seq += history.len() as u64;
                    history = messages;
                    if history.len() > max_messages {
                        let excess = history.len() - max_messages;
                        history.drain(0..excess);
                        base_seq += excess as u64;
                    }
                    let frame = sync_frame(&history, base_seq);
                    for id in &clients {
                        let _ = server.send_websocket_binary(*id, &frame);
                    }
                }
                Ok(WebFeed::ShareAvailable { stream_id, payload }) => {
                    active_shares.insert(stream_id, payload.clone());
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::ShareConfig(payload))
                | Ok(WebFeed::ShareError(payload))
                | Ok(WebFeed::FileProgress(payload)) => {
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::ShareEnded { stream_id, payload }) => {
                    active_shares.remove(&stream_id);
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::VideoFrame(frame)) => {
                    for id in &clients {
                        let _ = server.send_websocket_binary(*id, &frame);
                    }
                }
                Ok(WebFeed::Stop) => return,
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Disconnected) => return,
            }
        }
    }
}

/// The `sync` frame sent on connect: the most recent [`SYNC_WINDOW`] messages.
fn sync_frame(history: &[WebMessage], base_seq: u64) -> Vec<u8> {
    let start = history.len().saturating_sub(SYNC_WINDOW);
    web_wire::encode_window(
        web_wire::KIND_SYNC,
        &history[start..],
        base_seq + start as u64,
        start > 0,
    )
}

/// Builds the `older` frame for a `load_older` cursor: the `limit` messages
/// immediately before `before_seq`.
fn older_frame(before_seq: u64, limit: u64, history: &[WebMessage], base_seq: u64) -> Vec<u8> {
    // Clamp the cursor into the retained range, then take the `limit` messages
    // immediately before it.
    let end = before_seq
        .saturating_sub(base_seq)
        .min(history.len() as u64) as usize;
    let limit = (limit as usize).clamp(1, MAX_PAGE);
    let start = end.saturating_sub(limit);
    web_wire::encode_window(
        web_wire::KIND_OLDER,
        &history[start..end],
        base_seq + start as u64,
        start > 0,
    )
}

/// The JSON envelope sent on connect telling the browser whether it may compose.
fn config_envelope(readonly: bool) -> String {
    jsony::object! { type: "config", readonly: readonly }
}

/// An in-progress browser upload: the temp file its chunk frames stream into.
struct UploadSink {
    path: PathBuf,
    file: fs::File,
}

impl UploadSink {
    /// Creates the temp file for `upload_id` under a dedicated web-uploads
    /// directory, named from a sanitized `name` so the served file keeps a
    /// recognizable extension.
    fn create(upload_id: u32, name: &str) -> io::Result<Self> {
        let dir = std::env::temp_dir().join("chatt-web-uploads");
        fs::create_dir_all(&dir)?;
        let path = dir.join(format!("{upload_id}-{}", sanitize_upload_name(name)));
        let file = fs::File::create(&path)?;
        Ok(Self { path, file })
    }

    /// Appends one chunk's bytes to the temp file.
    fn append(&mut self, bytes: &[u8]) -> io::Result<()> {
        use std::io::Write;
        self.file.write_all(bytes)
    }
}

/// Reduces an uploaded file name to a flat, safe base name. Path separators and
/// parent references are stripped so the temp file never escapes its directory.
fn sanitize_upload_name(name: &str) -> String {
    let base = name.rsplit(['/', '\\']).next().unwrap_or(name);
    let trimmed = base.trim_matches('.');
    if trimmed.is_empty() {
        "upload".to_string()
    } else {
        trimmed.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_media_by_extension() {
        assert_eq!(classify("cat.PNG"), "image");
        assert_eq!(classify("clip.mp4"), "video");
        assert_eq!(classify("voice.opus"), "audio");
        assert_eq!(classify("archive.tar.gz"), "file");
        assert_eq!(classify("noext"), "file");
    }

    fn text_message(id: u64, body: &str) -> WebMessage {
        WebMessage::text_for_test(id, body)
    }

    #[test]
    fn highlight_name_validation_allows_flat_dotted_names() {
        assert!(valid_highlight_name("trace..old.rs"));
        assert!(valid_highlight_name("main.rs"));
        assert!(!valid_highlight_name(""));
        assert!(!valid_highlight_name("."));
        assert!(!valid_highlight_name(".."));
        assert!(!valid_highlight_name("nested/main.rs"));
        assert!(!valid_highlight_name(r"nested\main.rs"));
    }

    /// Parses a `load_older` request and builds its frame, mirroring the run
    /// loop's request handling.
    fn older_frame_for(request: &str, history: &[WebMessage], base_seq: u64) -> Option<Vec<u8>> {
        match jsony::from_json(request).ok()? {
            ClientRequest::LoadOlder { before_seq, limit } => {
                Some(older_frame(before_seq, limit, history, base_seq))
            }
            _ => None,
        }
    }

    #[test]
    fn sync_frame_wraps_recent_window() {
        let history = vec![text_message(7, "hi")];
        let window = web_wire::decode_window(&sync_frame(&history, 0));
        assert_eq!(window.kind, web_wire::KIND_SYNC);
        assert_eq!(window.oldest_seq, 0);
        assert!(!window.has_more);
        assert_eq!(window.messages.len(), 1);
        assert_eq!(window.messages[0].sender, "Alice");
    }

    #[test]
    fn sync_frame_caps_window_and_flags_more() {
        let history: Vec<WebMessage> = (0..SYNC_WINDOW as u64 + 5)
            .map(|i| text_message(i, "m"))
            .collect();
        let window = web_wire::decode_window(&sync_frame(&history, 0));
        // Only the last SYNC_WINDOW messages, starting at seq 5, with older
        // history still available.
        assert_eq!(window.oldest_seq, 5);
        assert!(window.has_more);
        assert_eq!(window.messages.len(), SYNC_WINDOW);
    }

    #[test]
    fn older_frame_returns_window_before_cursor() {
        let history: Vec<WebMessage> = (0..10).map(|i| text_message(i, "m")).collect();
        // Ask for the 3 messages before seq 5, while base_seq is 0.
        let request = r#"{"type":"load_older","before_seq":5,"limit":3}"#;
        let frame = older_frame_for(request, &history, 0).expect("valid request");
        let window = web_wire::decode_window(&frame);
        assert_eq!(window.kind, web_wire::KIND_OLDER);
        assert_eq!(window.oldest_seq, 2);
        assert!(window.has_more);
        assert_eq!(window.messages.len(), 3);
    }

    #[test]
    fn older_frame_clears_more_at_start() {
        let history: Vec<WebMessage> = (0..10).map(|i| text_message(i, "m")).collect();
        let request = r#"{"type":"load_older","before_seq":2,"limit":50}"#;
        let frame = older_frame_for(request, &history, 0).expect("valid request");
        let window = web_wire::decode_window(&frame);
        assert_eq!(window.oldest_seq, 0);
        assert!(!window.has_more);
        assert_eq!(window.messages.len(), 2);
    }

    #[test]
    fn older_frame_rejects_garbage() {
        let history = vec![text_message(0, "m")];
        assert!(older_frame_for("not json", &history, 0).is_none());
        assert!(older_frame_for(r#"{"type":"other"}"#, &history, 0).is_none());
    }

    use rpc::control::FileMetadata;
    use rpc::ids::{FileTransferId, RoomId, UserId};

    #[test]
    fn from_file_uses_served_name_for_attachment() {
        let metadata = FileMetadata {
            transfer_id: FileTransferId(3),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "wide.png".to_string(),
            original_name: "wide.png".to_string(),
            size: 10,
            timestamp_ms: 5,
        };
        // A save-time collision renamed the file on disk.
        let message = WebMessage::from_file(&metadata, "wide-1.png", Some((640, 480)));
        let attachment = message.attachment.as_ref().expect("attachment present");
        assert_eq!(attachment.name, "wide-1.png");
        assert_eq!(attachment.kind, "image");
        assert_eq!(attachment.width, Some(640));
        assert_eq!(attachment.height, Some(480));

        // The encoded frame carries the served name in its attachment.
        let frame = web_wire::encode_single(&message);
        let window_like =
            web_wire::encode_window(web_wire::KIND_SYNC, &[message.clone()], 0, false);
        let decoded = web_wire::decode_window(&window_like);
        assert_eq!(
            decoded.messages[0].attachment_name.as_deref(),
            Some("wide-1.png")
        );
        assert!(!frame.is_empty());

        // The file id carries the transfer id and the body keeps the size, so the
        // inline message correlates with and reads like its announcement.
        assert_eq!(message.file_id, Some(3));
        let Fragment::Text(body) = &message.fragments[0] else {
            panic!("expected a text fragment");
        };
        assert_eq!(body, "sent file `wide.png` (10 B)");
    }

    fn file_metadata(transfer_id: u64) -> FileMetadata {
        FileMetadata {
            transfer_id: FileTransferId(transfer_id),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "wide.png".to_string(),
            original_name: "wide.png".to_string(),
            size: 2048,
            timestamp_ms: 5,
        }
    }

    #[test]
    fn file_announcement_carries_file_id() {
        use rpc::control::ChatMessage;
        use rpc::ids::MessageId;
        let announcement = ChatMessage {
            message_id: MessageId(99),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            timestamp_ms: 5,
            body: "sent file `wide.png` (2.0 KiB)".to_string(),
            file_transfer_id: Some(FileTransferId(7)),
        };
        let message: WebMessage = (&announcement).into();
        // The file id keys the upsert, and the message id matches it so the
        // placeholder shares an id with the inline version that enriches it.
        assert_eq!(message.file_id, Some(7));
        assert_eq!(message.id, 7);
        assert!(message.attachment.is_none());
    }

    #[test]
    fn merge_enriches_placeholder_in_place() {
        let mut placeholder = file_placeholder(7, "sent file `wide.png` (2.0 KiB)");
        let inline = WebMessage::from_file(&file_metadata(7), "wide.png", Some((4, 2)));
        placeholder.merge_from(inline);
        let attachment = placeholder.attachment.as_ref().expect("attachment kept");
        assert_eq!(attachment.width, Some(4));
        assert_eq!(placeholder.file_id, Some(7));
    }

    #[test]
    fn merge_keeps_attachment_when_placeholder_arrives_last() {
        // Reverse order: the inline file arrived first, then the announcement.
        let mut inline = WebMessage::from_file(&file_metadata(7), "wide.png", Some((4, 2)));
        let placeholder = file_placeholder(7, "sent file `wide.png` (2.0 KiB)");
        inline.merge_from(placeholder);
        assert!(
            inline.attachment.is_some(),
            "a late placeholder must not drop the attachment"
        );
    }

    #[test]
    fn file_identity_includes_announcement_timestamp() {
        let first = WebMessage::from_file(&file_metadata(7), "first.png", None);
        let mut second_metadata = file_metadata(7);
        second_metadata.timestamp_ms += 1;
        let second = WebMessage::from_file(&second_metadata, "second.png", None);

        assert!(same_file(&first, &first));
        assert!(!same_file(&first, &second));
    }

    #[test]
    fn image_dimensions_parses_png_header() {
        let mut png = vec![0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
        png.extend_from_slice(&[0, 0, 0, 13]);
        png.extend_from_slice(b"IHDR");
        png.extend_from_slice(&100u32.to_be_bytes());
        png.extend_from_slice(&50u32.to_be_bytes());
        png.extend_from_slice(&[8, 2, 0, 0, 0]);
        assert_eq!(image_dimensions(&png), Some((100, 50)));
    }

    #[test]
    fn image_dimensions_rejects_non_image_bytes() {
        assert_eq!(image_dimensions(b"not an image"), None);
        assert_eq!(image_dimensions(&[]), None);
    }

    #[test]
    fn non_image_attachment_drops_dimensions() {
        let metadata = FileMetadata {
            transfer_id: FileTransferId(4),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "clip.mp4".to_string(),
            original_name: "clip.mp4".to_string(),
            size: 10,
            timestamp_ms: 5,
        };
        let message = WebMessage::from_file(&metadata, "clip.mp4", Some((1920, 1080)));
        let attachment = message.attachment.as_ref().expect("attachment present");
        assert_eq!(attachment.kind, "video");
        assert_eq!(attachment.width, None);
        assert_eq!(attachment.height, None);
    }

    /// A file announcement placeholder: a file id and body but no attachment yet.
    fn file_placeholder(id: u64, body: &str) -> WebMessage {
        WebMessage {
            id,
            sender: "Alice".to_string(),
            fragments: split_fragments(body),
            timestamp_ms: 5,
            attachment: None,
            file_id: Some(id),
        }
    }

    #[test]
    fn text_message_encodes_without_attachment() {
        let message = WebMessage::text_for_test(1, "hi");
        let frame = web_wire::encode_window(web_wire::KIND_SYNC, &[message], 0, false);
        let decoded = web_wire::decode_window(&frame);
        assert!(decoded.messages[0].attachment_name.is_none());
    }

    use std::io::{Read, Write};
    use std::net::TcpStream;
    use std::time::Duration;

    #[test]
    fn highlight_endpoint_serves_file_buffer() {
        let dir = std::env::temp_dir().join(format!("chatt-hl-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("trace..old.rs"), "fn main() {}\n").unwrap();

        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39521".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, Some(dir.clone()), 100, web_tx, true).unwrap();

        let mut stream = TcpStream::connect("127.0.0.1:39521").unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(
                b"GET /highlight/trace..old.rs HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n",
            )
            .unwrap();
        let headers = read_http_headers(&mut stream);
        assert!(headers.starts_with("HTTP/1.1 200 OK"), "{headers}");
        assert!(headers.contains("application/octet-stream"), "{headers}");

        let mut body = Vec::new();
        stream.read_to_end(&mut body).unwrap();
        // The first byte is the format version; a Rust body highlights a keyword.
        assert_eq!(body[0], 1);
        assert!(body.contains(&crate::highlight::HlClass::Keyword.as_u8()));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn highlight_endpoint_rejects_large_file() {
        let dir = std::env::temp_dir().join(format!("chatt-hl-large-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let large = vec![b'a'; MAX_HIGHLIGHT_FILE_BYTES as usize + 1];
        std::fs::write(dir.join("large.txt"), large).unwrap();

        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39523".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, Some(dir.clone()), 100, web_tx, true).unwrap();

        let mut stream = TcpStream::connect("127.0.0.1:39523").unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(b"GET /highlight/large.txt HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n")
            .unwrap();
        let headers = read_http_headers(&mut stream);
        assert!(
            headers.starts_with("HTTP/1.1 413 Payload Too Large"),
            "{headers}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn highlight_endpoint_rejects_missing_file() {
        let dir = std::env::temp_dir().join(format!("chatt-hl-miss-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39522".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, Some(dir.clone()), 100, web_tx, true).unwrap();

        let mut stream = TcpStream::connect("127.0.0.1:39522").unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(b"GET /highlight/absent.rs HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n")
            .unwrap();
        let headers = read_http_headers(&mut stream);
        assert!(headers.starts_with("HTTP/1.1 404"), "{headers}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    fn read_http_headers(stream: &mut TcpStream) -> String {
        let mut out = Vec::new();
        let mut byte = [0u8; 1];
        while !out.ends_with(b"\r\n\r\n") {
            stream.read_exact(&mut byte).unwrap();
            out.push(byte[0]);
        }
        String::from_utf8(out).unwrap()
    }

    fn read_ws_frame(stream: &mut TcpStream) -> (u8, Vec<u8>) {
        let mut head = [0u8; 2];
        stream.read_exact(&mut head).unwrap();
        let opcode = head[0] & 0x0f;
        let mut len = (head[1] & 0x7f) as usize;
        if len == 126 {
            let mut ext = [0u8; 2];
            stream.read_exact(&mut ext).unwrap();
            len = u16::from_be_bytes(ext) as usize;
        } else if len == 127 {
            let mut ext = [0u8; 8];
            stream.read_exact(&mut ext).unwrap();
            len = u64::from_be_bytes(ext) as usize;
        }
        let mut payload = vec![0u8; len];
        stream.read_exact(&mut payload).unwrap();
        (opcode, payload)
    }

    #[test]
    fn live_message_broadcasts_to_connected_client() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39517".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        let mut stream = TcpStream::connect("127.0.0.1:39517").unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(
                b"GET /ws HTTP/1.1\r\n\
Host: localhost\r\n\
Upgrade: websocket\r\n\
Connection: Upgrade\r\n\
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n\
Sec-WebSocket-Version: 13\r\n\
\r\n",
            )
            .unwrap();

        let headers = read_http_headers(&mut stream);
        assert!(
            headers.starts_with("HTTP/1.1 101 Switching Protocols"),
            "{headers}"
        );

        // The feed frames are binary (opcode 0x2). The first is an empty sync.
        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x2);
        let sync = web_wire::decode_window(&payload);
        assert_eq!(sync.kind, web_wire::KIND_SYNC);
        assert!(sync.messages.is_empty());

        // The config envelope follows the sync frame as a text frame.
        let (opcode, _) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);

        sender.send(WebMessage::text_for_test(1, "hello web"));

        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x2);
        let message = web_wire::decode_single(&payload);
        assert_eq!(
            message.fragments,
            vec![Fragment::Text("hello web".to_string())]
        );
    }

    /// Sends a client-to-server text frame, which RFC 6455 requires to be masked.
    fn write_ws_text(stream: &mut TcpStream, text: &str) {
        let bytes = text.as_bytes();
        assert!(bytes.len() < 126, "test payloads stay in the short length");
        let mask = [0x37u8, 0xfa, 0x21, 0x3d];
        let mut frame = vec![0x81, 0x80 | bytes.len() as u8];
        frame.extend_from_slice(&mask);
        for (i, byte) in bytes.iter().enumerate() {
            frame.push(byte ^ mask[i % 4]);
        }
        stream.write_all(&frame).unwrap();
    }

    /// Sends a client-to-server binary frame, masked as RFC 6455 requires.
    fn write_ws_binary(stream: &mut TcpStream, payload: &[u8]) {
        assert!(
            payload.len() < 126,
            "test payloads stay in the short length"
        );
        let mask = [0x37u8, 0xfa, 0x21, 0x3d];
        let mut frame = vec![0x82, 0x80 | payload.len() as u8];
        frame.extend_from_slice(&mask);
        for (i, byte) in payload.iter().enumerate() {
            frame.push(byte ^ mask[i % 4]);
        }
        stream.write_all(&frame).unwrap();
    }

    /// Consumes the config envelope that follows the sync frame on every connect.
    fn drain_config(stream: &mut TcpStream) {
        let (opcode, config) = read_ws_frame(stream);
        assert_eq!(opcode, 0x1);
        assert!(String::from_utf8(config).unwrap().contains("\"config\""));
    }

    /// Opens a browser feed, draining the sync frame and the config envelope that
    /// always follow a connect, and returns the socket ready for live frames.
    fn open_ready_ws(addr: &str) -> TcpStream {
        let mut stream = open_ws(addr);
        let (_, sync) = read_ws_frame(&mut stream);
        assert_eq!(web_wire::decode_window(&sync).kind, web_wire::KIND_SYNC);
        drain_config(&mut stream);
        stream
    }

    fn open_ws(addr: &str) -> TcpStream {
        let mut stream = TcpStream::connect(addr).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(
                b"GET /ws HTTP/1.1\r\n\
Host: localhost\r\n\
Upgrade: websocket\r\n\
Connection: Upgrade\r\n\
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n\
Sec-WebSocket-Version: 13\r\n\
\r\n",
            )
            .unwrap();
        let headers = read_http_headers(&mut stream);
        assert!(
            headers.starts_with("HTTP/1.1 101 Switching Protocols"),
            "{headers}"
        );
        stream
    }

    #[test]
    fn set_room_replaces_backlog_and_resyncs() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39520".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        let mut stream = open_ws("127.0.0.1:39520");
        let (_, sync) = read_ws_frame(&mut stream);
        assert!(web_wire::decode_window(&sync).messages.is_empty());
        drain_config(&mut stream);

        // Entering a room re-syncs the connected browser with that room's history.
        sender.set_room(vec![WebMessage::text_for_test(1, "room one")]);
        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x2);
        let window = web_wire::decode_window(&payload);
        assert_eq!(window.kind, web_wire::KIND_SYNC);
        assert_eq!(
            window.messages[0].fragments,
            vec![Fragment::Text("room one".to_string())]
        );

        // Leaving the room clears the view to nothing.
        sender.set_room(Vec::new());
        let (_, cleared) = read_ws_frame(&mut stream);
        let window = web_wire::decode_window(&cleared);
        assert_eq!(window.kind, web_wire::KIND_SYNC);
        assert!(window.messages.is_empty());
    }

    #[test]
    fn load_older_request_returns_older_frame() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39518".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        let mut stream = open_ws("127.0.0.1:39518");
        // Drain the initial empty sync frame and the config envelope.
        let (_, payload) = read_ws_frame(&mut stream);
        assert_eq!(web_wire::decode_window(&payload).kind, web_wire::KIND_SYNC);
        drain_config(&mut stream);

        // Three live messages take sequence numbers 0, 1, 2.
        for i in 0..3 {
            sender.send(WebMessage::text_for_test(i, &format!("m{i}")));
            let _ = read_ws_frame(&mut stream);
        }

        // Page the two messages before seq 2.
        write_ws_text(
            &mut stream,
            r#"{"type":"load_older","before_seq":2,"limit":5}"#,
        );
        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x2);
        let window = web_wire::decode_window(&payload);
        assert_eq!(window.kind, web_wire::KIND_OLDER);
        assert_eq!(window.oldest_seq, 0);
        assert!(!window.has_more);
        let bodies: Vec<&Fragment> = window
            .messages
            .iter()
            .flat_map(|message| &message.fragments)
            .collect();
        assert_eq!(
            bodies,
            vec![
                &Fragment::Text("m0".to_string()),
                &Fragment::Text("m1".to_string()),
            ]
        );
    }

    #[test]
    fn share_available_replays_to_late_client_until_ended() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39519".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        // A share starts before any browser connects.
        sender.send_share_available(
            5,
            "{\"type\":\"share_available\",\"stream_id\":5}".to_string(),
        );

        // A browser that connects after the share still learns it is available:
        // the retained announcement follows the initial sync frame.
        let mut late = open_ws("127.0.0.1:39519");
        let (_, sync) = read_ws_frame(&mut late);
        assert_eq!(web_wire::decode_window(&sync).kind, web_wire::KIND_SYNC);
        drain_config(&mut late);
        // Share announcements stay JSON text frames (opcode 0x1).
        let (opcode, payload) = read_ws_frame(&mut late);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(payload).unwrap();
        assert!(text.contains("\"share_available\""), "{text}");
        assert!(text.contains("\"stream_id\":5"), "{text}");

        // The share ends, dropping the retained announcement.
        sender.send_share_ended(5, "{\"type\":\"share_ended\",\"stream_id\":5}".to_string());
        let (_, ended) = read_ws_frame(&mut late);
        assert!(
            String::from_utf8(ended)
                .unwrap()
                .contains("\"share_ended\"")
        );

        // A browser that connects now sees no share. After sync, the next frame
        // is a live chat message, with no stale share_available before it.
        let mut fresh = open_ws("127.0.0.1:39519");
        let (_, sync2) = read_ws_frame(&mut fresh);
        assert_eq!(web_wire::decode_window(&sync2).kind, web_wire::KIND_SYNC);
        drain_config(&mut fresh);
        sender.send(WebMessage::text_for_test(1, "hi"));
        // The next frame is the live message (binary), not a stale share.
        let (opcode, next) = read_ws_frame(&mut fresh);
        assert_eq!(opcode, 0x2);
        let message = web_wire::decode_single(&next);
        assert_eq!(message.fragments, vec![Fragment::Text("hi".to_string())]);
    }

    #[test]
    fn config_envelope_reports_readonly_on_connect() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39524".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        let mut stream = open_ws("127.0.0.1:39524");
        // The sync frame comes first, then the config envelope as a text frame.
        let (opcode, sync) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x2);
        assert_eq!(web_wire::decode_window(&sync).kind, web_wire::KIND_SYNC);
        let (opcode, config) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(config).unwrap();
        assert!(text.contains("\"config\""), "{text}");
        assert!(text.contains("\"readonly\":true"), "{text}");
    }

    #[test]
    fn send_message_forwards_when_writable() {
        let cfg = WebConfig {
            enabled: true,
            readonly: false,
            bind: "127.0.0.1:39525".to_string(),
        };
        let (web_tx, web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, None, 100, web_tx, false).unwrap();

        let mut stream = open_ready_ws("127.0.0.1:39525");
        write_ws_text(&mut stream, r#"{"type":"send_message","body":"hi there"}"#);

        let request = web_rx.recv_timeout(Duration::from_secs(2)).unwrap();
        assert_eq!(
            request,
            WebRequest::SendChat {
                body: "hi there".to_string()
            }
        );
    }

    #[test]
    fn send_message_ignored_when_readonly() {
        let cfg = WebConfig {
            enabled: true,
            readonly: true,
            bind: "127.0.0.1:39526".to_string(),
        };
        let (web_tx, web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, None, 100, web_tx, true).unwrap();

        let mut stream = open_ready_ws("127.0.0.1:39526");
        write_ws_text(&mut stream, r#"{"type":"send_message","body":"hi there"}"#);

        // A read-only feed drops the write, so nothing reaches the app.
        assert!(web_rx.recv_timeout(Duration::from_millis(300)).is_err());
    }

    #[test]
    fn chunked_upload_assembles_temp_file() {
        let cfg = WebConfig {
            enabled: true,
            readonly: false,
            bind: "127.0.0.1:39527".to_string(),
        };
        let (web_tx, web_rx) = mpsc::channel();
        let _sender = spawn(&cfg, None, 100, web_tx, false).unwrap();

        let mut stream = open_ready_ws("127.0.0.1:39527");
        write_ws_text(
            &mut stream,
            r#"{"type":"upload_start","upload_id":42,"name":"note.txt","size":11}"#,
        );
        // A chunk frame is the little-endian upload id followed by the bytes.
        let mut chunk = 42u32.to_le_bytes().to_vec();
        chunk.extend_from_slice(b"hello world");
        write_ws_binary(&mut stream, &chunk);
        write_ws_text(&mut stream, r#"{"type":"upload_finish","upload_id":42}"#);

        let request = web_rx.recv_timeout(Duration::from_secs(2)).unwrap();
        let WebRequest::UploadFile { path } = request else {
            panic!("expected an upload request, got {request:?}");
        };
        assert_eq!(fs::read(&path).unwrap(), b"hello world");
        assert!(
            path.file_name()
                .unwrap()
                .to_str()
                .unwrap()
                .ends_with("note.txt")
        );
        let _ = fs::remove_file(&path);
    }
}
