//! The browser chat-log view served over [`darkhttp`].
//!
//! A dedicated thread owns the [`Server`] and runs its blocking poll loop. The
//! app forwards messages through a [`WebFeedSender`], which delivers them over an
//! `mpsc` channel and wakes the loop via a [`darkhttp::WakeHandle`] so they
//! broadcast immediately. On connect a client receives a recent window of
//! history, then a frame per new message. A browser pages older history on
//! demand by sending a `load_older` request as it scrolls up, addressed by a
//! server-assigned monotonic sequence number.

use std::io;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::mpsc::{self, Receiver, Sender, TryRecvError};
use std::thread;
use std::time::Duration;

use darkhttp::{
    Router, Server, ServerConfig, ServerEvent, WakeHandle, WebSocketId, WebSocketMessage,
};
use jsony::Jsony;
use rpc::control::{ChatMessage, FileMetadata};

use crate::config::WebConfig;

/// The path a browser opens a WebSocket on for the live feed.
const WS_PATH: &str = "/ws";
#[cfg(not(feature = "embed-web"))]
const WEB_ASSETS_DIR: &str = "web/dist";

/// The frontend compiled into the binary under the `embed-web` feature. The
/// `asset` resolver is generated by the web build into `web/dist/embed.rs`.
#[cfg(feature = "embed-web")]
mod embed {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/embed.rs"));
}

/// How many of the most recent messages a fresh `sync` frame carries. Older
/// history is paged in on demand.
const SYNC_WINDOW: usize = 100;

/// Upper bound on the messages one `load_older` request can return, so a
/// misbehaving client cannot ask for an unbounded slice.
const MAX_PAGE: usize = 200;

/// A single chat entry in the JSON view the frontend renders.
#[derive(Clone, Jsony)]
#[jsony(Json)]
pub struct WebMessage {
    pub id: u64,
    pub sender: String,
    pub body: String,
    pub timestamp_ms: u64,
    pub attachment: Option<WebAttachment>,
    /// `Some` for a file message. The feed upserts by this id together with
    /// `timestamp_ms`, because transfer ids are reused after a server restart.
    pub file_id: Option<u64>,
}

/// An inline media file attached to a [`WebMessage`], served from `/files`.
#[derive(Clone, Jsony)]
#[jsony(Json)]
pub struct WebAttachment {
    /// The served file name. The frontend builds the URL as `/files/<name>`.
    pub name: String,
    /// One of `image`, `video`, `audio`, or `file`.
    pub kind: String,
    /// Intrinsic pixel width, set for `image` attachments whose header parsed.
    ///
    /// The frontend reserves the box from `width`/`height` so a decoding image
    /// never grows the layout. `None` for non-images or an unreadable header.
    pub width: Option<u32>,
    /// Intrinsic pixel height, paired with [`width`](WebAttachment::width).
    pub height: Option<u32>,
}

impl From<&ChatMessage> for WebMessage {
    fn from(message: &ChatMessage) -> Self {
        let file_id = message.file_transfer_id.map(|transfer_id| transfer_id.0);
        WebMessage {
            // A file announcement keys on the transfer id so it shares an id with
            // the inline file message that later enriches it.
            id: file_id.unwrap_or(message.message_id.0),
            sender: message.sender_name.clone(),
            body: message.body.clone(),
            timestamp_ms: message.timestamp_ms,
            attachment: None,
            file_id,
        }
    }
}

impl WebMessage {
    /// Builds a message representing a received file, with an inline attachment.
    ///
    /// `served_name` is the file's actual name on disk under the receive
    /// directory, which is what `/files/<name>` resolves. It can differ from
    /// `metadata.file_name` when a name collision was renamed on save.
    ///
    /// `dimensions`, when set, is the intrinsic pixel size of an image. It is
    /// recorded only for the `image` kind so the frontend can reserve the box.
    pub fn from_file(
        metadata: &FileMetadata,
        served_name: &str,
        dimensions: Option<(u32, u32)>,
    ) -> Self {
        let kind = classify(served_name);
        let (width, height) = match (kind, dimensions) {
            ("image", Some((w, h))) => (Some(w), Some(h)),
            _ => (None, None),
        };
        WebMessage {
            id: metadata.transfer_id.0,
            sender: metadata.sender_name.clone(),
            // Mirror the server's announcement body so the size metadata survives
            // whichever of the two messages wins the upsert merge.
            body: format!(
                "sent file `{}` ({})",
                metadata.original_name,
                format_size(metadata.size)
            ),
            timestamp_ms: metadata.timestamp_ms,
            attachment: Some(WebAttachment {
                kind: kind.to_string(),
                name: served_name.to_string(),
                width,
                height,
            }),
            file_id: Some(metadata.transfer_id.0),
        }
    }
}

impl WebMessage {
    /// Builds a file message from persisted history: the chat announcement plus
    /// the stored served name and image dimensions. Used to populate the web
    /// backlog with a room's file messages when the room is entered.
    pub fn from_history_file(
        message: &ChatMessage,
        served_name: &str,
        dimensions: Option<(u32, u32)>,
    ) -> Self {
        let kind = classify(served_name);
        let (width, height) = match (kind, dimensions) {
            ("image", Some((w, h))) => (Some(w), Some(h)),
            _ => (None, None),
        };
        let file_id = message.file_transfer_id.map(|transfer_id| transfer_id.0);
        WebMessage {
            id: file_id.unwrap_or(message.message_id.0),
            sender: message.sender_name.clone(),
            body: message.body.clone(),
            timestamp_ms: message.timestamp_ms,
            attachment: Some(WebAttachment {
                kind: kind.to_string(),
                name: served_name.to_string(),
                width,
                height,
            }),
            file_id,
        }
    }
}

impl WebMessage {
    /// Folds a later message for the same file into this one. Order-independent:
    /// the incoming fields win, but an attachment is never dropped, so the inline
    /// version's media survives whether it arrives before or after the
    /// announcement placeholder.
    fn merge_from(&mut self, incoming: WebMessage) {
        let attachment = incoming.attachment.or_else(|| self.attachment.take());
        *self = WebMessage {
            attachment,
            ..incoming
        };
    }
}

fn same_file(left: &WebMessage, right: &WebMessage) -> bool {
    left.file_id.is_some()
        && left.file_id == right.file_id
        && left.timestamp_ms == right.timestamp_ms
}

/// Formats a byte count the way the server's file announcement does, so an
/// enriched file message reads identically to its placeholder.
fn format_size(bytes: u64) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * KIB;
    if bytes >= MIB {
        format!("{:.1} MiB", bytes as f64 / MIB as f64)
    } else if bytes >= KIB {
        format!("{:.1} KiB", bytes as f64 / KIB as f64)
    } else {
        format!("{bytes} B")
    }
}

/// Reads the intrinsic pixel size of an image from a prefix of its bytes.
///
/// Parses only the header fields, so a leading slice of the file is enough. The
/// caller captures that slice as the transfer streams, so the bytes are never
/// read from disk a second time. Returns `None` when `header` is not a
/// recognized image or is too short to hold the dimensions.
pub fn image_dimensions(header: &[u8]) -> Option<(u32, u32)> {
    let size = imagesize::blob_size(header).ok()?;
    Some((size.width as u32, size.height as u32))
}

/// Classifies a file name into a media kind by its extension.
pub(crate) fn classify(name: &str) -> &'static str {
    let extension = name.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match extension.as_str() {
        "png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp" | "svg" | "avif" => "image",
        "mp4" | "webm" | "mov" | "mkv" => "video",
        "mp3" | "ogg" | "opus" | "wav" | "flac" | "m4a" | "aac" => "audio",
        _ => "file",
    }
}

/// What the app sends to the web thread.
enum WebFeed {
    Message(WebMessage),
    /// Replaces the backlog with the current room's messages (empty when there
    /// is no current room) and re-syncs every connected browser. The web view
    /// mirrors the room the client is in, nothing more.
    SetRoom(Vec<WebMessage>),
    /// A `share_available` envelope. The web thread retains it by `stream_id` and
    /// replays it to a browser that connects after the share started.
    ShareAvailable {
        stream_id: u32,
        payload: String,
    },
    /// A `share_config` envelope sent when playback starts. Transient: it targets
    /// a browser that already asked to play, so it is broadcast but not retained.
    ShareConfig(String),
    /// A `share_error` envelope reporting a failed play request. Transient and
    /// broadcast like [`ShareConfig`](WebFeed::ShareConfig), not retained.
    ShareError(String),
    /// A `share_ended` envelope. Drops the retained `share_available` for its
    /// `stream_id`.
    ShareEnded {
        stream_id: u32,
        payload: String,
    },
    /// One plaintext video frame body (the 17-byte header plus the bitstream),
    /// forwarded to browsers as a binary WebSocket message without re-framing.
    VideoFrame(Vec<u8>),
    Stop,
}

/// A request a browser sends back to the app, forwarded over the web-to-app
/// channel. Screen-share playback is browser-initiated, so a play click must
/// reach the app to spawn the viewer connection.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum WebRequest {
    PlayShare { stream_id: u32 },
    StopShare { stream_id: u32 },
}

/// A request a browser sends over the WebSocket.
#[derive(Jsony)]
#[jsony(Json, tag = "type")]
enum ClientRequest {
    /// Asks for up to `limit` messages immediately older than `before_seq`.
    #[jsony(rename = "load_older")]
    LoadOlder { before_seq: u64, limit: u64 },
    /// Asks the app to start streaming a screen share into this browser.
    #[jsony(rename = "play_share")]
    PlayShare { stream_id: u32 },
    /// Asks the app to stop streaming a screen share.
    #[jsony(rename = "stop_share")]
    StopShare { stream_id: u32 },
}

/// A cloneable handle the app uses to push messages to the web view.
///
/// [`send`](WebFeedSender::send) queues the message and wakes the server's poll
/// loop, so a connected browser sees it without any polling delay. Sends never
/// fail loudly: a dead web thread must not break the chat client.
#[derive(Clone)]
pub struct WebFeedSender {
    tx: Sender<WebFeed>,
    wake: WakeHandle,
}

impl WebFeedSender {
    /// Pushes a message to every connected browser and records it in history.
    pub fn send(&self, message: WebMessage) {
        let _ = self.tx.send(WebFeed::Message(message));
        self.wake.wake();
    }

    /// Replaces the feed's backlog with `messages` and re-syncs every browser.
    ///
    /// Call this on entering a room (with that room's history) and on leaving
    /// one (with an empty vector) so the web view always shows exactly the
    /// current room's content.
    pub fn set_room(&self, messages: Vec<WebMessage>) {
        let _ = self.tx.send(WebFeed::SetRoom(messages));
        self.wake.wake();
    }

    /// Announces a screen share to every browser, retained so a browser that
    /// connects later still learns the share is available.
    pub fn send_share_available(&self, stream_id: u32, payload: String) {
        let _ = self.tx.send(WebFeed::ShareAvailable { stream_id, payload });
        self.wake.wake();
    }

    /// Sends a decoder-config envelope when playback starts. Not retained.
    pub fn send_share_config(&self, payload: String) {
        let _ = self.tx.send(WebFeed::ShareConfig(payload));
        self.wake.wake();
    }

    /// Sends a play-failure envelope to the browser. Not retained.
    pub fn send_share_error(&self, payload: String) {
        let _ = self.tx.send(WebFeed::ShareError(payload));
        self.wake.wake();
    }

    /// Tells every browser a share ended and drops its retained announcement.
    pub fn send_share_ended(&self, stream_id: u32, payload: String) {
        let _ = self.tx.send(WebFeed::ShareEnded { stream_id, payload });
        self.wake.wake();
    }

    /// Sends one plaintext video frame body as a binary WebSocket message.
    pub fn send_video_frame(&self, frame: Vec<u8>) {
        let _ = self.tx.send(WebFeed::VideoFrame(frame));
        self.wake.wake();
    }

    pub fn stop(&self) {
        let _ = self.tx.send(WebFeed::Stop);
        self.wake.wake();
    }
}

/// Starts the web server on its own thread and returns a feed handle.
///
/// `receive_dir`, when set, is mounted at `/files` so inline media resolves.
/// `max_messages` bounds the in-memory history replayed to new clients.
///
/// # Errors
///
/// Returns an error if `cfg.bind` is not a valid socket address or the listener
/// cannot bind.
pub fn spawn(
    cfg: &WebConfig,
    receive_dir: Option<PathBuf>,
    max_messages: usize,
    web_requests: Sender<WebRequest>,
) -> io::Result<WebFeedSender> {
    let addr: SocketAddr = cfg.bind.parse().map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid web.bind `{}`: {error}", cfg.bind),
        )
    })?;

    let mut router = Router::new().websocket(WS_PATH);
    if let Some(dir) = receive_dir {
        router = router.mount_file_dir("/files", dir);
    }
    #[cfg(not(feature = "embed-web"))]
    {
        router = router.mount_static_dir("/", PathBuf::from(WEB_ASSETS_DIR));
    }
    #[cfg(feature = "embed-web")]
    {
        router = router.embedded_assets(embed::asset);
    }

    // A zero timeout disables idle-connection reaping so a quiet WebSocket is
    // never closed out from under a watching browser.
    let config = ServerConfig::default().bind(addr).timeout(Duration::ZERO);
    let server = Server::bind(config, router)?;
    let wake = server.wake_handle()?;
    let local = server.local_addr()?;

    let (tx, rx) = mpsc::channel();
    thread::Builder::new()
        .name("web-server".to_string())
        .spawn(move || run(server, rx, max_messages, web_requests))?;

    kvlog::info!("web server listening", addr = %local);
    Ok(WebFeedSender { tx, wake })
}

/// The web thread's event loop. Blocks until a socket event or a feed wake.
fn run(
    mut server: Server,
    rx: Receiver<WebFeed>,
    max_messages: usize,
    web_requests: Sender<WebRequest>,
) {
    let mut history: Vec<WebMessage> = Vec::new();
    // The sequence number of `history[0]`. Sequence numbers are monotonic across
    // the whole feed and survive front-draining, so a browser can address older
    // history independent of the message ids (which span two id namespaces).
    let mut base_seq: u64 = 0;
    let mut clients: Vec<WebSocketId> = Vec::new();
    // Active screen shares by stream id, replayed to a browser that connects
    // after a share started so it still shows the play button.
    let mut active_shares: std::collections::HashMap<u32, String> =
        std::collections::HashMap::new();

    loop {
        if let Err(error) = server.poll_once(None) {
            kvlog::error!("web server poll failed", error = %error);
            return;
        }

        for event in server.drain_events() {
            match event {
                ServerEvent::WebSocketOpen { id, path } => {
                    if path == WS_PATH {
                        clients.push(id);
                        let _ = server.send_websocket_text(id, sync_payload(&history, base_seq));
                        for payload in active_shares.values() {
                            let _ = server.send_websocket_text(id, payload);
                        }
                    }
                }
                ServerEvent::WebSocketClose { id } => clients.retain(|client| *client != id),
                ServerEvent::WebSocketMessage {
                    id,
                    message: WebSocketMessage::Text(text),
                } => match jsony::from_json::<ClientRequest>(&text) {
                    Ok(ClientRequest::LoadOlder { before_seq, limit }) => {
                        let payload = older_window_payload(before_seq, limit, &history, base_seq);
                        let _ = server.send_websocket_text(id, &payload);
                    }
                    Ok(ClientRequest::PlayShare { stream_id }) => {
                        let _ = web_requests.send(WebRequest::PlayShare { stream_id });
                    }
                    Ok(ClientRequest::StopShare { stream_id }) => {
                        let _ = web_requests.send(WebRequest::StopShare { stream_id });
                    }
                    Err(_) => {}
                },
                ServerEvent::WebSocketMessage { .. } => {}
            }
        }

        loop {
            match rx.try_recv() {
                Ok(WebFeed::Message(message)) => {
                    // A file message upserts onto its existing entry (the
                    // announcement placeholder, or the inline version if it
                    // arrived first), so a file is one message enriched in place,
                    // never two. The seq is preserved, so paging is untouched.
                    let existing = message.file_id.and_then(|_| {
                        history
                            .iter_mut()
                            .rev()
                            .find(|held| same_file(held, &message))
                    });
                    let payload = if let Some(existing) = existing {
                        existing.merge_from(message);
                        message_payload(existing)
                    } else {
                        let payload = message_payload(&message);
                        history.push(message);
                        if history.len() > max_messages {
                            let excess = history.len() - max_messages;
                            history.drain(0..excess);
                            base_seq += excess as u64;
                        }
                        payload
                    };
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::SetRoom(messages)) => {
                    // Advance the sequence past the dropped backlog so a browser
                    // never confuses the new room's messages with the old ones,
                    // then bound the replacement to the same window as live sends.
                    base_seq += history.len() as u64;
                    history = messages;
                    if history.len() > max_messages {
                        let excess = history.len() - max_messages;
                        history.drain(0..excess);
                        base_seq += excess as u64;
                    }
                    let payload = sync_payload(&history, base_seq);
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::ShareAvailable { stream_id, payload }) => {
                    active_shares.insert(stream_id, payload.clone());
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::ShareConfig(payload)) | Ok(WebFeed::ShareError(payload)) => {
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::ShareEnded { stream_id, payload }) => {
                    active_shares.remove(&stream_id);
                    for id in &clients {
                        let _ = server.send_websocket_text(*id, &payload);
                    }
                }
                Ok(WebFeed::VideoFrame(frame)) => {
                    for id in &clients {
                        let _ = server.send_websocket_binary(*id, &frame);
                    }
                }
                Ok(WebFeed::Stop) => return,
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Disconnected) => return,
            }
        }
    }
}

/// The `sync` envelope sent on connect: the most recent [`SYNC_WINDOW`] messages.
fn sync_payload(history: &[WebMessage], base_seq: u64) -> String {
    let start = history.len().saturating_sub(SYNC_WINDOW);
    window_payload(
        "sync",
        &history[start..],
        base_seq + start as u64,
        start > 0,
    )
}

/// Builds the `older` envelope for a `load_older` cursor: the `limit` messages
/// immediately before `before_seq`.
fn older_window_payload(
    before_seq: u64,
    limit: u64,
    history: &[WebMessage],
    base_seq: u64,
) -> String {
    // Clamp the cursor into the retained range, then take the `limit` messages
    // immediately before it.
    let end = before_seq
        .saturating_sub(base_seq)
        .min(history.len() as u64) as usize;
    let limit = (limit as usize).clamp(1, MAX_PAGE);
    let start = end.saturating_sub(limit);
    window_payload(
        "older",
        &history[start..end],
        base_seq + start as u64,
        start > 0,
    )
}

/// Builds the `older` envelope answering a `load_older` request, or [`None`] if
/// the request does not parse. Retained for unit tests of the parse-and-build path.
#[cfg(test)]
fn older_payload(text: &str, history: &[WebMessage], base_seq: u64) -> Option<String> {
    match jsony::from_json(text).ok()? {
        ClientRequest::LoadOlder { before_seq, limit } => {
            Some(older_window_payload(before_seq, limit, history, base_seq))
        }
        _ => None,
    }
}

/// Serializes a window of messages with its paging cursor.
///
/// `oldest_seq` is the sequence number of the first message in `messages`.
/// `has_more` is true when still-older retained history exists before it.
fn window_payload(kind: &str, messages: &[WebMessage], oldest_seq: u64, has_more: bool) -> String {
    let messages = jsony::to_json(messages);
    format!(
        "{{\"type\":\"{kind}\",\"messages\":{messages},\"oldest_seq\":{oldest_seq},\"has_more\":{has_more}}}"
    )
}

/// The `message` envelope sent for each new message.
fn message_payload(message: &WebMessage) -> String {
    let message = jsony::to_json(message);
    format!("{{\"type\":\"message\",\"message\":{message}}}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_media_by_extension() {
        assert_eq!(classify("cat.PNG"), "image");
        assert_eq!(classify("clip.mp4"), "video");
        assert_eq!(classify("voice.opus"), "audio");
        assert_eq!(classify("archive.tar.gz"), "file");
        assert_eq!(classify("noext"), "file");
    }

    fn text_message(id: u64, body: &str) -> WebMessage {
        WebMessage {
            id,
            sender: "Alice".to_string(),
            body: body.to_string(),
            timestamp_ms: 100,
            attachment: None,
            file_id: None,
        }
    }

    #[test]
    fn sync_payload_wraps_recent_window() {
        let history = vec![text_message(7, "hi")];
        let payload = sync_payload(&history, 0);
        assert!(payload.starts_with("{\"type\":\"sync\",\"messages\":["));
        assert!(payload.contains("\"sender\":\"Alice\""));
        assert!(payload.contains("\"oldest_seq\":0"));
        assert!(payload.contains("\"has_more\":false"));
    }

    #[test]
    fn sync_payload_caps_window_and_flags_more() {
        let history: Vec<WebMessage> = (0..SYNC_WINDOW as u64 + 5)
            .map(|i| text_message(i, "m"))
            .collect();
        let payload = sync_payload(&history, 0);
        // Only the last SYNC_WINDOW messages, starting at seq 5, with older
        // history still available.
        assert!(payload.contains("\"oldest_seq\":5"));
        assert!(payload.contains("\"has_more\":true"));
        assert_eq!(payload.matches("\"sender\"").count(), SYNC_WINDOW);
    }

    #[test]
    fn older_payload_returns_window_before_cursor() {
        let history: Vec<WebMessage> = (0..10).map(|i| text_message(i, "m")).collect();
        // Ask for the 3 messages before seq 5, while base_seq is 0.
        let request = r#"{"type":"load_older","before_seq":5,"limit":3}"#;
        let payload = older_payload(request, &history, 0).expect("valid request");
        assert!(payload.starts_with("{\"type\":\"older\","));
        assert!(payload.contains("\"oldest_seq\":2"));
        assert!(payload.contains("\"has_more\":true"));
        assert_eq!(payload.matches("\"sender\"").count(), 3);
    }

    #[test]
    fn older_payload_clears_more_at_start() {
        let history: Vec<WebMessage> = (0..10).map(|i| text_message(i, "m")).collect();
        let request = r#"{"type":"load_older","before_seq":2,"limit":50}"#;
        let payload = older_payload(request, &history, 0).expect("valid request");
        assert!(payload.contains("\"oldest_seq\":0"));
        assert!(payload.contains("\"has_more\":false"));
        assert_eq!(payload.matches("\"sender\"").count(), 2);
    }

    #[test]
    fn older_payload_rejects_garbage() {
        let history = vec![text_message(0, "m")];
        assert!(older_payload("not json", &history, 0).is_none());
        assert!(older_payload(r#"{"type":"other"}"#, &history, 0).is_none());
    }

    use rpc::control::FileMetadata;
    use rpc::ids::{FileTransferId, RoomId, UserId};

    #[test]
    fn from_file_uses_served_name_for_attachment() {
        let metadata = FileMetadata {
            transfer_id: FileTransferId(3),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "wide.png".to_string(),
            original_name: "wide.png".to_string(),
            size: 10,
            timestamp_ms: 5,
        };
        // A save-time collision renamed the file on disk.
        let message = WebMessage::from_file(&metadata, "wide-1.png", Some((640, 480)));
        let attachment = message.attachment.as_ref().expect("attachment present");
        assert_eq!(attachment.name, "wide-1.png");
        assert_eq!(attachment.kind, "image");
        assert_eq!(attachment.width, Some(640));
        assert_eq!(attachment.height, Some(480));

        let json = jsony::to_json(&message);
        assert!(json.contains("\"attachment\":{"), "{json}");
        assert!(json.contains("\"name\":\"wide-1.png\""), "{json}");

        // The file id carries the transfer id and the body keeps the size, so the
        // inline message correlates with and reads like its announcement.
        assert_eq!(message.file_id, Some(3));
        assert_eq!(message.body, "sent file `wide.png` (10 B)");
    }

    fn file_metadata(transfer_id: u64) -> FileMetadata {
        FileMetadata {
            transfer_id: FileTransferId(transfer_id),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "wide.png".to_string(),
            original_name: "wide.png".to_string(),
            size: 2048,
            timestamp_ms: 5,
        }
    }

    #[test]
    fn file_announcement_carries_file_id() {
        use rpc::control::ChatMessage;
        use rpc::ids::MessageId;
        let announcement = ChatMessage {
            message_id: MessageId(99),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            timestamp_ms: 5,
            body: "sent file `wide.png` (2.0 KiB)".to_string(),
            file_transfer_id: Some(FileTransferId(7)),
        };
        let message: WebMessage = (&announcement).into();
        // The file id keys the upsert, and the message id matches it so the
        // placeholder shares an id with the inline version that enriches it.
        assert_eq!(message.file_id, Some(7));
        assert_eq!(message.id, 7);
        assert!(message.attachment.is_none());
    }

    #[test]
    fn merge_enriches_placeholder_in_place() {
        let mut placeholder: WebMessage = WebMessage {
            id: 7,
            sender: "Alice".to_string(),
            body: "sent file `wide.png` (2.0 KiB)".to_string(),
            timestamp_ms: 5,
            attachment: None,
            file_id: Some(7),
        };
        let inline = WebMessage::from_file(&file_metadata(7), "wide.png", Some((4, 2)));
        placeholder.merge_from(inline);
        let attachment = placeholder.attachment.as_ref().expect("attachment kept");
        assert_eq!(attachment.width, Some(4));
        assert_eq!(placeholder.file_id, Some(7));
    }

    #[test]
    fn merge_keeps_attachment_when_placeholder_arrives_last() {
        // Reverse order: the inline file arrived first, then the announcement.
        let mut inline = WebMessage::from_file(&file_metadata(7), "wide.png", Some((4, 2)));
        let placeholder = WebMessage {
            id: 7,
            sender: "Alice".to_string(),
            body: "sent file `wide.png` (2.0 KiB)".to_string(),
            timestamp_ms: 5,
            attachment: None,
            file_id: Some(7),
        };
        inline.merge_from(placeholder);
        assert!(
            inline.attachment.is_some(),
            "a late placeholder must not drop the attachment"
        );
    }

    #[test]
    fn file_identity_includes_announcement_timestamp() {
        let first = WebMessage::from_file(&file_metadata(7), "first.png", None);
        let mut second_metadata = file_metadata(7);
        second_metadata.timestamp_ms += 1;
        let second = WebMessage::from_file(&second_metadata, "second.png", None);

        assert!(same_file(&first, &first));
        assert!(!same_file(&first, &second));
    }

    #[test]
    fn image_dimensions_parses_png_header() {
        let mut png = vec![0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
        png.extend_from_slice(&[0, 0, 0, 13]);
        png.extend_from_slice(b"IHDR");
        png.extend_from_slice(&100u32.to_be_bytes());
        png.extend_from_slice(&50u32.to_be_bytes());
        png.extend_from_slice(&[8, 2, 0, 0, 0]);
        assert_eq!(image_dimensions(&png), Some((100, 50)));
    }

    #[test]
    fn image_dimensions_rejects_non_image_bytes() {
        assert_eq!(image_dimensions(b"not an image"), None);
        assert_eq!(image_dimensions(&[]), None);
    }

    #[test]
    fn non_image_attachment_drops_dimensions() {
        let metadata = FileMetadata {
            transfer_id: FileTransferId(4),
            room_id: RoomId(1),
            sender: UserId(2),
            sender_name: "Alice".to_string(),
            file_name: "clip.mp4".to_string(),
            original_name: "clip.mp4".to_string(),
            size: 10,
            timestamp_ms: 5,
        };
        let message = WebMessage::from_file(&metadata, "clip.mp4", Some((1920, 1080)));
        let attachment = message.attachment.as_ref().expect("attachment present");
        assert_eq!(attachment.kind, "video");
        assert_eq!(attachment.width, None);
        assert_eq!(attachment.height, None);
    }

    #[test]
    fn text_message_serializes_null_attachment() {
        let message = WebMessage {
            id: 1,
            sender: "Bob".to_string(),
            body: "hi".to_string(),
            timestamp_ms: 0,
            attachment: None,
            file_id: None,
        };
        assert!(jsony::to_json(&message).contains("\"attachment\":null"));
    }

    use std::io::{Read, Write};
    use std::net::TcpStream;
    use std::time::Duration;

    fn read_http_headers(stream: &mut TcpStream) -> String {
        let mut out = Vec::new();
        let mut byte = [0u8; 1];
        while !out.ends_with(b"\r\n\r\n") {
            stream.read_exact(&mut byte).unwrap();
            out.push(byte[0]);
        }
        String::from_utf8(out).unwrap()
    }

    fn read_ws_frame(stream: &mut TcpStream) -> (u8, Vec<u8>) {
        let mut head = [0u8; 2];
        stream.read_exact(&mut head).unwrap();
        let opcode = head[0] & 0x0f;
        let mut len = (head[1] & 0x7f) as usize;
        if len == 126 {
            let mut ext = [0u8; 2];
            stream.read_exact(&mut ext).unwrap();
            len = u16::from_be_bytes(ext) as usize;
        } else if len == 127 {
            let mut ext = [0u8; 8];
            stream.read_exact(&mut ext).unwrap();
            len = u64::from_be_bytes(ext) as usize;
        }
        let mut payload = vec![0u8; len];
        stream.read_exact(&mut payload).unwrap();
        (opcode, payload)
    }

    #[test]
    fn live_message_broadcasts_to_connected_client() {
        let cfg = WebConfig {
            enabled: true,
            bind: "127.0.0.1:39517".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx).unwrap();

        let mut stream = TcpStream::connect("127.0.0.1:39517").unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(
                b"GET /ws HTTP/1.1\r\n\
Host: localhost\r\n\
Upgrade: websocket\r\n\
Connection: Upgrade\r\n\
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n\
Sec-WebSocket-Version: 13\r\n\
\r\n",
            )
            .unwrap();

        let headers = read_http_headers(&mut stream);
        assert!(
            headers.starts_with("HTTP/1.1 101 Switching Protocols"),
            "{headers}"
        );

        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);
        assert_eq!(
            payload,
            b"{\"type\":\"sync\",\"messages\":[],\"oldest_seq\":0,\"has_more\":false}"
        );

        sender.send(WebMessage {
            id: 1,
            sender: "Bob".to_string(),
            body: "hello web".to_string(),
            timestamp_ms: 42,
            attachment: None,
            file_id: None,
        });

        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(payload).unwrap();
        assert!(text.starts_with("{\"type\":\"message\""), "{text}");
        assert!(text.contains("\"body\":\"hello web\""), "{text}");
    }

    /// Sends a client-to-server text frame, which RFC 6455 requires to be masked.
    fn write_ws_text(stream: &mut TcpStream, text: &str) {
        let bytes = text.as_bytes();
        assert!(bytes.len() < 126, "test payloads stay in the short length");
        let mask = [0x37u8, 0xfa, 0x21, 0x3d];
        let mut frame = vec![0x81, 0x80 | bytes.len() as u8];
        frame.extend_from_slice(&mask);
        for (i, byte) in bytes.iter().enumerate() {
            frame.push(byte ^ mask[i % 4]);
        }
        stream.write_all(&frame).unwrap();
    }

    fn open_ws(addr: &str) -> TcpStream {
        let mut stream = TcpStream::connect(addr).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        stream
            .write_all(
                b"GET /ws HTTP/1.1\r\n\
Host: localhost\r\n\
Upgrade: websocket\r\n\
Connection: Upgrade\r\n\
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n\
Sec-WebSocket-Version: 13\r\n\
\r\n",
            )
            .unwrap();
        let headers = read_http_headers(&mut stream);
        assert!(
            headers.starts_with("HTTP/1.1 101 Switching Protocols"),
            "{headers}"
        );
        stream
    }

    #[test]
    fn set_room_replaces_backlog_and_resyncs() {
        let cfg = WebConfig {
            enabled: true,
            bind: "127.0.0.1:39520".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx).unwrap();

        let mut stream = open_ws("127.0.0.1:39520");
        let (_, sync) = read_ws_frame(&mut stream);
        assert!(String::from_utf8(sync).unwrap().contains("\"messages\":[]"));

        // Entering a room re-syncs the connected browser with that room's history.
        sender.set_room(vec![WebMessage {
            id: 1,
            sender: "Alice".to_string(),
            body: "room one".to_string(),
            timestamp_ms: 1,
            attachment: None,
            file_id: None,
        }]);
        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(payload).unwrap();
        assert!(text.starts_with("{\"type\":\"sync\""), "{text}");
        assert!(text.contains("\"body\":\"room one\""), "{text}");

        // Leaving the room clears the view to nothing.
        sender.set_room(Vec::new());
        let (_, cleared) = read_ws_frame(&mut stream);
        let text = String::from_utf8(cleared).unwrap();
        assert!(text.starts_with("{\"type\":\"sync\""), "{text}");
        assert!(text.contains("\"messages\":[]"), "{text}");
    }

    #[test]
    fn load_older_request_returns_older_frame() {
        let cfg = WebConfig {
            enabled: true,
            bind: "127.0.0.1:39518".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx).unwrap();

        let mut stream = open_ws("127.0.0.1:39518");
        // Drain the initial empty sync frame.
        let (_, payload) = read_ws_frame(&mut stream);
        assert!(String::from_utf8(payload).unwrap().contains("\"sync\""));

        // Three live messages take sequence numbers 0, 1, 2.
        for i in 0..3 {
            sender.send(WebMessage {
                id: i,
                sender: "Bob".to_string(),
                body: format!("m{i}"),
                timestamp_ms: 1,
                attachment: None,
                file_id: None,
            });
            let _ = read_ws_frame(&mut stream);
        }

        // Page the two messages before seq 2.
        write_ws_text(
            &mut stream,
            r#"{"type":"load_older","before_seq":2,"limit":5}"#,
        );
        let (opcode, payload) = read_ws_frame(&mut stream);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(payload).unwrap();
        assert!(text.starts_with("{\"type\":\"older\""), "{text}");
        assert!(text.contains("\"oldest_seq\":0"), "{text}");
        assert!(text.contains("\"has_more\":false"), "{text}");
        assert!(text.contains("\"body\":\"m0\""), "{text}");
        assert!(text.contains("\"body\":\"m1\""), "{text}");
        assert!(!text.contains("\"body\":\"m2\""), "{text}");
    }

    #[test]
    fn share_available_replays_to_late_client_until_ended() {
        let cfg = WebConfig {
            enabled: true,
            bind: "127.0.0.1:39519".to_string(),
        };
        let (web_tx, _web_rx) = mpsc::channel();
        let sender = spawn(&cfg, None, 100, web_tx).unwrap();

        // A share starts before any browser connects.
        sender.send_share_available(
            5,
            "{\"type\":\"share_available\",\"stream_id\":5}".to_string(),
        );

        // A browser that connects after the share still learns it is available:
        // the retained announcement follows the initial sync frame.
        let mut late = open_ws("127.0.0.1:39519");
        let (_, sync) = read_ws_frame(&mut late);
        assert!(String::from_utf8(sync).unwrap().contains("\"sync\""));
        let (opcode, payload) = read_ws_frame(&mut late);
        assert_eq!(opcode, 0x1);
        let text = String::from_utf8(payload).unwrap();
        assert!(text.contains("\"share_available\""), "{text}");
        assert!(text.contains("\"stream_id\":5"), "{text}");

        // The share ends, dropping the retained announcement.
        sender.send_share_ended(5, "{\"type\":\"share_ended\",\"stream_id\":5}".to_string());
        let (_, ended) = read_ws_frame(&mut late);
        assert!(
            String::from_utf8(ended)
                .unwrap()
                .contains("\"share_ended\"")
        );

        // A browser that connects now sees no share. After sync, the next frame
        // is a live chat message, with no stale share_available before it.
        let mut fresh = open_ws("127.0.0.1:39519");
        let (_, sync2) = read_ws_frame(&mut fresh);
        assert!(String::from_utf8(sync2).unwrap().contains("\"sync\""));
        sender.send(WebMessage {
            id: 1,
            sender: "Bob".to_string(),
            body: "hi".to_string(),
            timestamp_ms: 0,
            attachment: None,
            file_id: None,
        });
        let (_, next) = read_ws_frame(&mut fresh);
        let text = String::from_utf8(next).unwrap();
        assert!(text.contains("\"message\""), "{text}");
        assert!(!text.contains("share_available"), "{text}");
    }
}
