[package]
name = "chatt-local-rpc"
version = "0.1.0"
edition = "2024"

[lib]
name = "local_rpc"

[dependencies]
chatt-ids = { path = "../ids" }
chatt-video = { path = "../video" }
jsony = "0.1.10"
kvlog = { git = "https://github.com/exrok/kvlog", rev = "0e3092abc1a0be07683b42e689a2acef7cf6014b", default-features = false }
libc = "0.2"
uuid = { version = "1.7.0", default-features = false }
