[package]
name = "chatt-local-rpc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
name = "local_rpc"

[dependencies]
chatt-ids = { path = "../ids" }
chatt-video = { path = "../video" }
jsony = "0.1.10"
kvlog = { git = "https://github.com/exrok/kvlog", rev = "139b426d2050b5f9ad646ab8097d86e8ab0728e9", default-features = false }
libc = "0.2"
uuid = { version = "1.7.0", default-features = false }
