[package]
name = "server"
version = "0.3.1"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "chatt-server"
path = "src/main.rs"

[dependencies]
jsony = "0.1.10"
rpc.path = "../rpc"
chatt-mls.path = "../mls"
mio = { version = "1.2.1", features = ["os-poll", "net"] }
aws-lc-rs = { version = "1.17.1", default-features = false, features = ["alloc", "non-fips"] }
kvlog = { git = "https://github.com/exrok/kvlog", rev = "139b426d2050b5f9ad646ab8097d86e8ab0728e9" }
annotate-snippets = "0.12.10"
toml-spanner = { version = "1.0.3", features = [
    "to-toml",
    "from-toml",
    "derive",
] }
libc = "0.2"
foldhash = "0.2.0"
hashbrown = "0.17.1"
mimalloc = { version = "0.1.52", features = ["override"] }
redb = "4.1"

[dev-dependencies]
tempfile = "3.27.0"
