// Postbuild generator for the Rust `embed-web` feature. After `vite build`, gzip
// every file in dist/ and write dist/embed.rs: a single `match`-based `asset()`
// the Rust client includes to serve the frontend from the binary. Rust cannot
// see Vite's content-hashed filenames otherwise, and this avoids a build.rs.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, posix, relative, sep } from "node:path";
import { gzipSync } from "node:zlib";

// Content types by extension, mirroring crates/darkhttp/src/http/mime.rs.
const MIME = {
  html: "text/html; charset=UTF-8",
  htm: "text/html; charset=UTF-8",
  css: "text/css; charset=UTF-8",
  js: "text/javascript; charset=UTF-8",
  mjs: "text/javascript; charset=UTF-8",
  json: "application/json",
  txt: "text/plain; charset=UTF-8",
  svg: "image/svg+xml",
  ico: "image/x-icon",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  avif: "image/avif",
  wasm: "application/wasm",
  pdf: "application/pdf",
  zip: "application/zip",
  mp3: "audio/mpeg",
  ogg: "audio/ogg",
  wav: "audio/wav",
  mp4: "video/mp4",
  webm: "video/webm",
};

function contentType(file) {
  const dot = file.lastIndexOf(".");
  const ext = dot < 0 ? "" : file.slice(dot + 1).toLowerCase();
  return MIME[ext] ?? "application/octet-stream";
}

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const dist = join(import.meta.dirname, "dist");
const arms = [];
for (const full of walk(dist)) {
  if (full.endsWith(".gz") || full.endsWith("embed.rs")) continue;
  const rel = relative(dist, full).split(sep).join(posix.sep);
  writeFileSync(`${full}.gz`, gzipSync(readFileSync(full), { level: 9 }));
  const route = `/${rel}`;
  // The root request resolves to index.html without a filesystem index fallback.
  const arm = rel === "index.html" ? `"/" | ${JSON.stringify(route)}` : JSON.stringify(route);
  arms.push(
    `        ${arm} => (\n` +
      `            ${JSON.stringify(contentType(rel))}, "gzip", include_bytes!(${JSON.stringify(`${rel}.gz`)})),`,
  );
}

const body =
  "// @generated by the web build (gen-embed.mjs) — do not edit.\n" +
  "pub fn asset(path: &str) -> Option<(&'static str, &'static str, &'static [u8])> {\n" +
  "    Some(match path {\n" +
  `${arms.join("\n")}\n` +
  "        _ => return None,\n" +
  "    })\n" +
  "}\n";
writeFileSync(join(dist, "embed.rs"), body);
console.log(`embed.rs: ${arms.length} assets`);
